<s> ::= [?xml version=%1.0% encoding=%UTF-8%?]<cf>
<cf> ::= <sequence> | <selector>
<sequence> ::= [Sequence]<execution>[/Sequence] | [Sequence]<cf><cf>[/Sequence] | [Sequence]<sequence> <cf>[/Sequence]
<selector> ::= [Selector]<execution>[/Selector] | [Selector]<cf><cf>[/Selector] | [Selector]<selector> <cf>[/Selector]
<execution>::=<conditions>[act]<action>[/act]
<conditions>::=[cond]<condition>[/cond]<conditions>|[cond]<condition>[/cond]
<condition>::=NeighbourObjects|IsDropable_<sobjects>|NeighbourObjects_<objects>|NeighbourObjects_<objects>_invert|IsVisitedBefore_<sobjects>|IsVisitedBefore_<sobjects>_invert|IsCarrying_<dobjects>|IsCarrying_<dobjects>_invert|IsInPartialAttached_<dobjects>|IsInPartialAttached_<dobjects>_invert
<action>::=MoveTowards_<sobjects>|Explore|CompositeSingleCarry_<dobjects>|CompositeDrop_<dobjects>|MoveAway_<sobjects>|CompositeMultipleCarry_<dobjects>|CompositeDropPartial_<dobjects>|CompositeDropCue_<sobjects>|CompositePickCue_Cue|CompositeSendSignal_<sobjects>|CompositeReceiveSignal_Signal
<sobjects>::=Hub|Sites|Obstacles
<dobjects>::=Food|Debris
<cobjects>::=Signal|Cue
<objects>::=<sobjects>|<dobjects>