<s> ::= [?xml version=%1.0% encoding=%UTF-8%?]<cf>
<cf> ::= <sequence> | <selector>
<sequence> ::= [Sequence]<execution>[/Sequence] | [Sequence]<cf><cf>[/Sequence] | [Sequence]<sequence> <cf>[/Sequence]
<selector> ::= [Selector]<execution>[/Selector] | [Selector]<cf><cf>[/Selector] | [Selector]<selector> <cf>[/Selector]
<execution>::=<conditions>[act]<action>[/act]
<conditions>::=[cond]<condition>[/cond]<conditions>|[cond]<condition>[/cond]
<condition>::=NeighbourObjects|NeighbourObjects_<objects>|NeighbourObjects_<objects>_invert|IsVisitedBefore_<sobjects>|IsVisitedBefore_<sobjects>_invert|IsInPartialAttached_<dobjects>|IsInPartialAttached_<dobjects>_invert
<action>::=MoveTowards_<sobjects>|Explore|MoveAway_<sobjects>|CompositeMultipleCarry_<dobjects>|CompositeDropPartial_<dobjects>
<sobjects>::=Hub|Sites
<dobjects>::=Food
<objects>::=<sobjects>|<dobjects>