<s> ::= [?xml version=%1.0% encoding=%UTF-8%?]<root>
<root> ::= [Sequence]<ppa><ppa><ppa><ppa><ppa>[/Sequence]
<ppa>  ::= <ppaA> | <ppaB> | <ppaD> | <ppaE> | <ppaC>
<ppaA> ::= [Sequence][Selector]<postcondition><lastSelectorA>[/Selector]<postcondition>[/Sequence]
<ppaB> ::= [Sequence][Selector]<postcondition><lastSelectorB>[/Selector]<postcondition>[/Sequence]
<ppaC> ::= [Sequence][Selector]<postcondition><lastSelectorC>[/Selector]<postcondition>[/Sequence]
<ppaD> ::= [Sequence][Selector]<postcondition><lastSelectorD>[/Selector]<postcondition>[/Sequence]
<ppaE> ::= [Sequence][Selector]<postcondition><lastSelectorE>[/Selector]<postcondition>[/Sequence]
<postcondition> ::= <postcondition>[PostCnd]<postconditiont>[/PostCnd]|[PostCnd]<postconditiont>[/PostCnd]
<postconditiont> ::= NeighbourObjects_<objects>|NeighbourObjects_<sobjects>|NeighbourObjects_<dobjects>|DidAvoidedObj_<sobjects>|IsCarrying_<dobjects>|IsVisitedBefore_<sobjects>
<lastSelectorA> ::=  [Sequence]<preconditions>[Act]<actiona>[/Act][/Sequence]
<lastSelectorB> ::=  [Sequence]<preconditions>[Act]<actionb>[/Act][/Sequence]
<lastSelectorC> ::=  [Sequence]<preconditions>[Act]<actionc>[/Act][/Sequence]
<lastSelectorD> ::=  [Sequence]<preconditions>[Act]<actiond>[/Act][/Sequence]
<lastSelectorE> ::=  [Sequence]<preconditions>[Act]<actione>[/Act][/Sequence]
<preconditions> ::= [Sequence]<precondition>[/Sequence]
<precondition> ::= <precondition>[PreCnd]<preconditiont>[/PreCnd]|[PreCnd]<preconditiont>[/PreCnd]
<preconditiont> ::=IsDropable_<sobjects>|NeighbourObjects_<objects>|NeighbourObjects_<objects>_invert|IsVisitedBefore_<sobjects>|IsVisitedBefore_<sobjects>_invert|IsCarrying_<dobjects>|IsCarrying_<dobjects>_invert
<actiona> ::= Explore
<actionb> ::= MoveTowards_<sobjects>
<actionc> ::= MoveAway_<sobjects>
<actiond> ::= CompositeSingleCarry_<dobjects>
<actione> ::= CompositeDrop_<dobjects>
<sobjects>::=Hub|Sites
<dobjects>::=Food
<objects>::=<sobjects>|<dobjects>