<s> ::= [?xml version=%1.0% encoding=%UTF-8%?]<root>
<root> ::= [Parallel]<ppa><ppa><ppa><ppa><ppa>[/Parallel]
<ppa>  ::= <ppaA> | <ppaB> | <ppaD> | <ppaE> | <ppaC>
<ppaA> ::= [Selector]<lastSelectorA><leaveStateConds>[/Selector]
<ppaB> ::= [Selector]<lastSelectorB><leaveStateConds>[/Selector]
<ppaC> ::= [Selector]<lastSelectorC><leaveStateConds>[/Selector]
<ppaD> ::= [Selector]<lastSelectorD><leaveStateConds>[/Selector]
<ppaE> ::= [Selector]<lastSelectorE><leaveStateConds>[/Selector]
<enterStateCond> ::= NeighbourObjects_<objects>|NeighbourObjects_<sobjects>|NeighbourObjects_<dobjects>|IsCarrying_<dobjects>|IsVisitedBefore_<sobjects>|IsBored
<lastSelectorA> ::=  [Sequence][EnterCnd]<enterStateCond>[/EnterCnd][Act]<actiona>[/Act][/Sequence]
<lastSelectorB> ::=  [Sequence][EnterCnd]<enterStateCond>[/EnterCnd][Act]<actionb>[/Act][/Sequence]
<lastSelectorC> ::=  [Sequence][EnterCnd]<enterStateCond>[/EnterCnd][Act]<actionc>[/Act][/Sequence]
<lastSelectorD> ::=  [Sequence][EnterCnd]<enterStateCond>[/EnterCnd][Act]<actiond>[/Act][/Sequence]
<lastSelectorE> ::=  [Sequence][EnterCnd]<enterStateCond>[/EnterCnd][Act]<actione>[/Act][/Sequence]
<leaveStateConds> ::= [Selector]<leaveStateCond>[/Selector]
<leaveStateCond> ::= <leaveStateCond>[LeaveCnd]<leaveStateCondT>[/LeaveCnd]|[LeaveCnd]<leaveStateCondT>[/LeaveCnd]
# <leaveStateCondT> ::= IsDropable_<sobjects>|NeighbourObjects_<objects>|NeighbourObjects_<objects>_invert|IsVisitedBefore_<sobjects>|IsVisitedBefore_<sobjects>_invert|IsCarrying_<dobjects>|IsCarrying_<dobjects>_invert|IsBored
<leaveStateCondT> ::= NeighbourObjects_<objects>|NeighbourObjects_<sobjects>|NeighbourObjects_<dobjects>|IsCarrying_<dobjects>|IsVisitedBefore_<sobjects>|IsBored
<sobjects>::=Hub|Sites
<dobjects>::=Food
<objects>::=<sobjects>|<dobjects>
<actiona> ::= ExploreNormal
<actionb> ::= MoveTowardsNormal
<actionc> ::= MoveAwayNormal
<actiond> ::= CompositeSingleCarry
<actione> ::= CompositeDrop
