#!/usr/bin/bash
#@author: aadeshnpn

# Script to collect mean for same experiment based on the number of agents


expfold="/home/aadeshnpn/Documents/BYU/hcmi/hri/nest_maint/00100NestMAgents"

exp=($(find ${expfold} -type f -name mean*.npy | xargs ls -v ))

# echo "${exp[@]}"

python  << EOF
"""Script to draw performance graph for paper."""
import sys
from swarms.utils.graph import PMultCompGraph, PMultGraph


def main():
    """Parse args and call graph module."""
    fdir="${expfold}"
    filenames="${exp[@]}"
    filenames = filenames.split(' ')
    # print (filenames)
    box = PMultCompGraph(fdir, filenames, "Nest Maintenance")
    box.gen_plot()
    agraph = PMultGraph(fdir, filenames, "Nest Maintenance")
    agraph.gen_plot()

if __name__ == '__main__':
    main()
EOF